hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.showSql=true
hibernate.connection.driverClass=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/hotel_management_db
hibernate.connection.username=root
hibernate.connection.password=root
hikari.maximum.poolsize=20
hikari.minium.idle=2
hikari.timeout.idle=30000
user.page_size=10
room.page_size=25
service.page_size=10
voucher.page_size=10