
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


payment.vnp.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnp.tmnCode=K2HGK7K8
payment.vnp.hashSecret=IO460JZSRDKXG9V7XPNBUAIZFWV80DZ9
payment.vnp.version=2.1.0
payment.vnp.command=pay
payment.vnp.currCode=VND
payment.vnp.locale=vn
payment.vnp.orderType=other
payment.vnp.returnUrl=http://localhost:3000/receipt/{bookingId}



payment.zalo.endpoint=https://sb-openapi.zalopay.vn/v2/create
payment.zalo.appId=2553
payment.zalo.key1=PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL
payment.zalo.key2=kLtgPl8YESYV3apPNQ31YglRvT9s3cgM