# \u0110\u1ecbnh d\u1ea1ng: T\u00ean_hi\u1ec3n_th\u1ecb | Group | Icon_FontAwesome
sidebar.grp.dashboard=Danh s\u00e1ch ph\u00f2ng|dashboard|fa-chart-line
# \u0110\u1ecbnh d\u1ea1ng: T\u00ean_hi\u1ec3n_th\u1ecb | URL
sidebar.item.dashboard.xemBaoCao=Xem danh s\u00e1ch ph\u00f2ng|/admin/recept/dashboard




