# \u0110\u1ecbnh d\u1ea1ng: T\u00ean_hi\u1ec3n_th\u1ecb | Group | Icon_FontAwesome
sidebar.grp.dashboard=B\u00e1o C\u00e1o & Th\u1ed1ng K\u00ea|dashboard|fa-chart-line
# \u0110\u1ecbnh d\u1ea1ng: T\u00ean_hi\u1ec3n_th\u1ecb | URL
sidebar.item.dashboard.xemBaoCao=Xem b\u00e1o c\u00e1o|/admin/report/

sidebar.grp.luutru=Qu\u1ea3n L\u00fd L\u01b0u Tr\u00fa|luutru|fa-bed
sidebar.item.luutru.room=Danh s\u00e1ch Ph\u00f2ng|/admin/rooms/

sidebar.grp.account=T\u00e0i kho\u1ea3n|account|fa-user-alt
sidebar.item.account.list=Qu\u1ea3n l\u00fd t\u00e0i kho\u1ea3n|/admin/user/


